---
- name: Run in workers
  block:
  - name: Check init cluster k8s(it run first time and for adding new instance)
    #if run with become: yes then command is going as root and will be error
    become: false   
    shell: kubectl cluster-info
    register: rc_k8s
    ignore_errors: true

  - name: Init worker if one not init
    block:
    - name: Create directory
      file:
        path: $HOME/.kube/
        state: directory
        mode: '0755'

    - name: Copy config to workers from localhost for workers 
      copy:
        src: config
        dest: $HOME/.kube/config

    - name: Copy config to workers from localhost for workers 
      copy:
        src: "{{ role_path }}/files/join_for_workers.sh"
        dest: $HOME/join_for_workers.sh
        mode: '0775'

    - name: Add name of workers at the end of last line of init workers's file
      shell: sed -i "$ s/$/ --node-name {{ inventory_hostname }}/" join_for_workers.sh

    - name: Need run before join workers
      #become: true
      shell: yes | sudo kubeadm reset

    - name: Init workers(role_path - system variable)
      become: true
      shell: ./join_for_workers.sh
    become: false
    when: rc_k8s.rc == 1  
  when: "'ansible_workers' in group_names"