---
- name: Deploy web page(run in master)
  block:
  - name: Create secret for Amazon Elastic Block Store (EBS) CSI driver
    shell: |
      kubectl delete secret aws-secret --namespace kube-system
      key=$(sed -r '2!d;s/.*=//' .aws/credentials)
      access_key=$(sed -r '3!d;s/.*=//' .aws/credentials)
      kubectl create secret generic aws-secret \
        --namespace kube-system \
        --from-literal "key_id=${key}" \
        --from-literal "access_key=${access_key}"
    #sed - take 2 and 3 line and delete everything before "=" including "="
    #need .aws/credentials(02_init_master.yml)

  - name: Change secret-key in cm-alert.yaml for email
    shell: sed -ie "s/secret-key/$(sed '1!d' \.email\/secret-key.txt)/" helm_chart/templates/cm-alert.yaml
    #need .email/secret-key.txt(02_init_master.yml)

  - name: Install Amazon Elastic Block Store (EBS) CSI driver
    shell: kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.24"

  - name: Copy files to master from localhost to deploy Prometheus
    copy:
      src: helm_chart
      dest: $HOME

  - name: Generate values.yaml
    template: 
      src: values.j2
      dest: $HOME/helm_chart/values.yaml

  - name: Run prometheus and exporters
    shell: |
      cd helm_chart/
      while ! helm upgrade --install -n monitoring --create-namespace prometheus .; do sleep 5; done
      helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      helm repo update
      helm upgrade --install -n monitoring kube-state-metrics prometheus-community/kube-state-metrics
#      kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

  - name: Set DeleteOnTermination in "true" on volume created of Prometheus to be one will delete when we run command terraform destroy
    shell: |
      while ! aws ec2 modify-instance-attribute --instance-id \
        $(aws ec2 describe-volumes --filters Name=tag:pv,Values=prometheus --query 'Volumes[0].Attachments[0].InstanceId' --output text --region {{ region_from_terraform }}) \
        --block-device-mappings "[{\"DeviceName\": \
        \"$(aws ec2 describe-volumes --filters Name=tag:pv,Values=prometheus --query 'Volumes[0].Attachments[0].Device' --output text --region {{ region_from_terraform }})\",\
        \"Ebs\":{\"DeleteOnTermination\":true}}]" --region {{ region_from_terraform }}; do sleep 5; done
    #id=$(aws ec2 describe-volumes --filters Name=tag:pv,Values=prometheus --query 'Volumes[0].Attachments[0].InstanceId' --output text --region eu-north-1)
    #device=$(aws ec2 describe-volumes --filters Name=tag:pv,Values=prometheus --query 'Volumes[0].Attachments[0].Device' --output text --region eu-north-1)
    #aws ec2 modify-instance-attribute --instance-id $id --block-device-mappings "[{\"DeviceName\": \"$device\",\"Ebs\":{\"DeleteOnTermination\":true}}]" --region eu-north-1

  - name: Approve CSRs(to see 04_cert_kudeadm.yml)
    shell: for csr_name in $(kubectl get csr | grep -i pending | awk '{print $1}'); do kubectl certificate approve $csr_name; done

  become: false
  #if run with become: true(in ansible.cfg) then %HOME will be /root and all run will be as root  
  when: "'ansible_master' in group_names" 

- name: Run in workers
  block:
  - name: ff
    shell: while ! curl -X POST localhost:9090/-/reload; do sleep 5; done
    #pgrep prometheus | kill -HUP
  when: "'ansible_workers' in group_names"      

          #dns_sd_configs:
          #- names:
          #  - 'kube-dns.kube-system.svc'