---
# tasks file for k8s_deploy
- import_tasks: 01_install.yml
- import_tasks: 02_run_on_master.yml
- import_tasks: 03_run_on_workers.yml
- import_tasks: 04_coredns_ingress_controller.yml
- import_tasks: 05_build_image.yml
- import_tasks: 06_deploy_app.yml
