apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus-server
        image: prom/prometheus
        volumeMounts:
          - name: prometheus-config-volume
            mountPath: /etc/prometheus/prometheus.yml
            subPath: prometheus.yml
          - name: prometheus-data
            mountPath: /prometheus
        ports:
        - containerPort: 9090
      initContainers:
        - name: prometheus-data-permission-fix
          image: busybox
          command: ["/bin/chmod","-R","777", "/prometheus"]
          volumeMounts:
          - name: prometheus-data
            mountPath: /prometheus      
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config     
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: pvc-prometheus-data      