apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: prometheus
