apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  prometheus.yaml: |-
    {
      "apiVersion": 1,
      "datasources": [
        {
          "access":"proxy",
          "editable": true,
          "name": "prometheus",
          "orgId": 1,
          "type": "prometheus",
          "url": "http://prometheus.monitoring.svc.cluster.local:9090",
          "version": 1
        }
      ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-dashboards
data:
  default.yaml: |-
    apiVersion: 1
    providers:
      - name: dashboards
        FOLDER: Services
        type: file
        updateIntervalSeconds: 30
        options:
          path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
data:
  my-dashboard.yaml: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 1,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "P1809F7CD0C75ACF3"
          },
          "description": "",
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 2,
            "w": 3,
            "x": 0,
            "y": 0
          },
          "hideTimeOverride": true,
          "id": 1,
          "interval": "1",
          "options": {
            "colorMode": "value",
            "graphMode": "area",
            "justifyMode": "center",
            "orientation": "horizontal",
            "reduceOptions": {
              "calcs": [
                "firstNotNull"
              ],
              "fields": "/^Time$/",
              "values": false
            },
            "text": {
              "titleSize": 25,
              "valueSize": 35
            },
            "textMode": "value",
            "wideLayout": true
          },
          "pluginVersion": "10.2.2",
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "P1809F7CD0C75ACF3"
              },
              "editorMode": "code",
              "exemplar": false,
              "expr": "time()",
              "format": "time_series",
              "hide": false,
              "instant": false,
              "interval": "",
              "legendFormat": "__auto",
              "range": true,
              "refId": "A"
            }
          ],
          "timeFrom": "1s",
          "timeShift": "0h",
          "title": "Time",
          "transformations": [
            {
              "id": "formatTime",
              "options": {
                "outputFormat": "HH:mm:ss",
                "timeField": "Time",
                "useTimezone": true
              }
            }
          ],
          "transparent": true,
          "type": "stat"
        }
      ],
      "refresh": "5s",
      "schemaVersion": 38,
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "MyDash",
      "uid": "ebb73790-1df8-41a2-bb7f-63f37fefe079",
      "version": 1,
      "weekStart": ""
    }  