apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-config
#  labels:
#    app: blackbox-exporter
data:
  blackbox.yaml: |
    modules:    
      http_2xx:
        prober: http
        timeout: 5s      
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          method: GET
          valid_status_codes: []
          fail_if_ssl: false
          fail_if_not_ssl: false          
          preferred_ip_protocol: "ip4"